[package]
name = "lumiavis"
version = "0.2.0"
edition = "2026"
description = "Lightweight Rust library for camera capture, image processing, preview, and simple video pipelines"
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/alanersia/lumiavis"
homepage = "https://github.com/alanersia/lumiavis"
documentation = "https://docs.rs/lumiavis"
keywords = ["camera", "vision", "image", "video", "v4l2"]
categories = ["multimedia::images", "multimedia::video", "computer-vision"]

[dependencies]
image = "0.25.10"
minifb = "0.28.0"

[target.'cfg(target_os = "windows")'.dependencies]
windows = { version = "0.58", features = [
    "Win32_Media_MediaFoundation",
    "Win32_System_Com",
    "Win32_Foundation"
] }

[target.'cfg(target_os = "linux")'.dependencies]
v4l = { version = "0.14.0"}