pub mod backends;
pub mod capture;
pub mod core;
pub mod error;
pub mod image;
pub mod render;
pub mod video;

pub use crate::capture::camera::Camera;
pub use crate::capture::config::CameraConfig;
pub use crate::capture::session::{CaptureSession, CaptureStats};
pub use crate::core::camera_mode::CameraMode;
pub use crate::core::camera_state::CameraState;
pub use crate::core::frame::Frame;
pub use crate::core::frame_format::FrameFormat;
pub use crate::core::resolution::Resolution;
pub use crate::error::CamError;
pub use crate::image::decoder::decode_frame;
pub use crate::image::image::Image;
pub use crate::image::ops::crop::CropRect;
pub use crate::image::ops::grayscale::grayscale;
pub use crate::image::ops::resize::resize;
pub use crate::image::pixel_format::PixelFormat;
pub use crate::render::display::image_to_u32_buffer;
pub use crate::video::export::{Mp4ExportOptions, export_jpeg_sequence_to_mp4};
